[[pages]]
path = "main.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "qa_fm.py"
name = "QA - Single FM ğŸ“™"
icon = ":question:"

[[pages]]
path = "qa_fm_comparison.py"
name = "QA - FM Comparison ğŸ“š"
icon = ":question:"

[[pages]]
path = "chat_fm.py"
name = "Chat - FMs"
icon = ":robot_face:"

[[pages]]
path = "text_search.py"
name = "Text Search"
icon = ":mag_right:"

[[pages]]
path = "code_translation.py"
name = "Code Translation"
icon = ":abacus:"

[[pages]]
path = "rag_documents.py"
name = "RAG - Document(s)"
icon = ":file_folder:"

[[pages]]
path = "rag_www.py"
name = "RAG - WWW"
icon = ":globe_with_meridians:"


[[pages]]
path = "solutions_overview.py"
name = "Solutions Overview"
icon = ":triangular_ruler:"
